export const ADDPRODUCTTYPES = "ADD-NEW-PRODUCT";

export const GETALLPRODUCTS = "GET-ALL-PRODUCTS";

export const ADDCAROUSEL = "ADD-NEW-CAROUSEL";

export type ProductTypes =
  | "ADD-NEW-PRODUCT"
  | "GET-ALL-PRODUCTS"
  | "ADD-NEW-CAROUSEL";
