export const ADDPRODUCTTYPES = "ADD-NEW-PRODUCT";

export const GETALLPRODUCTS = "GET-ALL-PRODUCTS";

export const ADDCAROUSEL = "ADD-NEW-CAROUSEL";

export const GETALLCAROUSEL = "GET-ALL-CAROUSEL";

export const RESETPRODUCT = "RESET-ALL-PRODUCT";

export const DELETECAROUSEL = "DELETE-CAROUSEL";

export type ProductTypes =
  | "ADD-NEW-PRODUCT"
  | "GET-ALL-PRODUCTS"
  | "ADD-NEW-CAROUSEL"
  | "GET-ALL-CAROUSEL"
  | "RESET-ALL-PRODUCT"
  | "DELETE-CAROUSEL";
